version: '3'

services:
  database:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=rent-x

# version: '3.8'

# services:
#   db:
#     image: postgres
#     container_name: db-rent-x
#     restart: always
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=rent-x
#       - POSTGRES_PASSWORD=docker
#       - POSTGRES_DB=rent-x
#     volumes:
#       - pgdata:/data/postgres
#   app:
#     build: .
#     container_name: rent-x
#     ports:
#       - 3333:3333
#       - 9229:9229
#     volumes:
#       - .:/usr/app
#     links:
#       - db
#     depends_on:
#       - db


#   redis:
#     image: redis:alpine
#     ports:
#       - 6379:6379

# volumes:
#   pgdata:
#     driver: local
